config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :brightcove_settings
  end
end

app/models/spree.rb
module Spree
  def self.table_name_prefix
    'spree_'
  end
end

app/models/spree/app_configuration_decorator.rb
Spree::AppConfiguration.class_eval do
  preference :brightcove_account_id, :string
  preference :brightcove_player_id, :string
end

app/models/spree/brightcove_setting.rb
class Spree::BrightcoveSetting < ActiveRecord::Base

  validates :brightcove_account_id, presence: true
  validates :brightcove_player_id, uniqueness: {scope: [:brightcove_account_id, :active]}

  def self.current
    brightcove_setting = where(active: true).first
    brightcove_setting.brightcove_account_id.present? ? brightcove_setting : nil if brightcove_setting
  end
end

app/controllers/spree/admin/brightcove_settings_controller.rb
module Spree
  module Admin
    class BrightcoveSettingsController < ResourceController
      before_filter :get_object, except: [:new, :create]

      def new
        @brightcove_setting = Spree::BrightcoveSetting.new
      end

      def get_object
        @brightcove_setting = Spree::BrightcoveSetting.last
        @object = @brightcove_setting
      end

    end
  end
end

app/helpers/spree/base_helper_decorator.rb
# override base helper for few core fnctions
Spree::BaseHelper.class_eval do

  # current brightcove settings
  def get_brightcove_player()
    Spree::BrightcoveSetting.current
  end
end

app/views/spree/admin/brightcove_settings/_form.html.erb
<div data-hook="admin_brightcove_setting_form_fields" class="row">
  <div class="alpha four columns">
    <div data-hook="brightcove_account_id" class="field">
      <%= f.label :brightcove_account_id %>
      <%= f.text_field :brightcove_account_id, :class => 'fullwidth' %>
    </div>

    <div data-hook="brightcove_account_id" class="field">
      <%= f.label :brightcove_player_id %>
      <%= f.text_field :brightcove_player_id, :class => 'fullwidth' %>
    </div>

  </div>

  <div class="omega four columns">
    <div data-hook="active" class="field">
      <%= f.label :active %>
      <ul>
        <li>
          <%= radio_button(:brightcove_setting, :active, true) %>
          <%= label_tag :brightcove_setting_active_true, Spree.t(:say_yes) %>
        </li>
        <li>
          <%= radio_button(:brightcove_setting, :active, false) %>
          <%= label_tag :brightcove_setting_active_false, Spree.t(:say_no) %>
        </li>
      </ul>
    </div>
  </div>

  <div class="clear"></div>

  <div data-hook="additional_brightcove_setting_fields"></div>

</div>

app/views/spree/admin/brightcove_settings/edit.html.erb
<%= render 'spree/admin/shared/general_tabs' %>

<% admin_breadcrumb(Spree.t(:settings)) %>
<% admin_breadcrumb(Spree.t(:general_settings)) %>
<% admin_breadcrumb(link_to plural_resource_name(Spree::BrightcoveSetting), spree.admin_brightcove_settings_path) %>
<% admin_breadcrumb('Brightcove Setting') %>


<% content_for :page_actions do %>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @brightcove_setting } %>

<%= form_for [:admin, @brightcove_setting], url: admin_brightcove_settings_path do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/brightcove_settings/index.html.erb
<%= render 'spree/admin/shared/general_tabs' %>

<% admin_breadcrumb(Spree.t(:settings)) %>
<% admin_breadcrumb(Spree.t(:general_settings)) %>
<% admin_breadcrumb(plural_resource_name(Spree::BrightcoveSetting)) %>

<% content_for :page_actions do %>
  <% if can?(:create, Spree::BrightcoveSetting) %>
    <li>
      <%= button_link_to Spree.t(:new_brightcove_setting), new_object_url, :id => 'admin_new_brightcove_setting_link' %>
    </li>
  <% end %>
<% end %>

<% if @brightcove_settings.any? %>
  <table class="index">
    <colgroup>
      <col style="width: 30%">
      <col style="width: 40%">
      <col style="width: 15%">
      <col style="width: 15%">
    </colgroup>
    <thead>
      <tr data-hook="admin_brightcove_settings_index_headers">
        <th><%= Spree::BrightcoveSetting.human_attribute_name(:brightcove_account_id) %></th>
        <th><%= Spree::BrightcoveSetting.human_attribute_name(:brightcove_player_id) %></th>
        <th><%= Spree::BrightcoveSetting.human_attribute_name(:active) %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @brightcove_settings.each do |brightcove_setting|%>
        <tr id="<%= spree_dom_id brightcove_setting %>" data-hook="admin_brightcove_settings_index_rows" class="<%= cycle('odd', 'even')%>">
          <td class="align-center"><%= brightcove_setting.brightcove_account_id %></td>
          <td class="align-center"><%= brightcove_setting.brightcove_player_id %></td>
          <td class="align-center"><%= brightcove_setting.active ? Spree.t(:say_yes) : Spree.t(:say_no) %></td>
          <td class="actions">
            <% if can?(:update, brightcove_setting) %>
              <%= link_to_edit brightcove_setting, :no_text => true %>
            <% end %>

            <% if can?(:destroy, brightcove_setting) %>
              <%= link_to_delete brightcove_setting, :no_text => true %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
                 resource: Spree::BrightcoveSetting,
                 new_resource_url: new_object_url %>
  </div>
<% end %>


<h2>Current Video Player</h2>
<%= render partial: 'spree/shared/player', locals: {reference_id: Spree::Product.where.not(reference_id: nil).first.try(:reference_id)} %>

app/views/spree/admin/brightcove_settings/new.html.erb
<%= render 'spree/admin/shared/general_tabs' %>

<% admin_breadcrumb(Spree.t(:settings)) %>
<% admin_breadcrumb(Spree.t(:general_settings)) %>
<% admin_breadcrumb(link_to plural_resource_name(Spree::BrightcoveSetting), spree.admin_brightcove_settings_path) %>
<% admin_breadcrumb(Spree.t(:new_brightcove_setting)) %>

<% content_for :page_actions do %>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @brightcove_setting } %>

<%= form_for [:admin, @brightcove_setting] do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/brightcove_settings/show.html.erb
<%= render 'spree/admin/shared/general_tabs' %>

<% admin_breadcrumb(Spree.t(:settings)) %>
<% admin_breadcrumb(Spree.t(:general_settings)) %>
<% admin_breadcrumb(plural_resource_name(Spree::BrightcoveSetting)) %>

<% content_for :page_actions do %>
  <% if can?(:create, Spree::BrightcoveSetting) %>
    <li>
      <%= button_link_to Spree.t(:new_brightcove_setting), new_admin_brightcove_settings_path, :id => 'admin_new_brightcove_setting_link' %>
    </li>
  <% end %>
<% end %>

<%  unless @brightcove_setting.blank? %>
  <table class="index">
    <colgroup>
      <col style="width: 30%">
      <col style="width: 40%">
      <col style="width: 15%">
      <col style="width: 15%">
    </colgroup>
    <thead>
      <tr data-hook="admin_brightcove_settings_index_headers">
        <th><%= Spree::BrightcoveSetting.human_attribute_name(:brightcove_account_id) %></th>
        <th><%= Spree::BrightcoveSetting.human_attribute_name(:brightcove_player_id) %></th>
        <th><%= Spree::BrightcoveSetting.human_attribute_name(:active) %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
        <tr id="<%= spree_dom_id @brightcove_setting %>" data-hook="admin_brightcove_settings_index_rows" class="<%= cycle('odd', 'even')%>">
          <td class="align-center"><%= @brightcove_setting.brightcove_account_id %></td>
          <td class="align-center"><%= @brightcove_setting.brightcove_player_id %></td>
          <td class="align-center"><%= @brightcove_setting.active ? Spree.t(:say_yes) : Spree.t(:say_no) %></td>
          <td class="actions">
            <% if can?(:update, @brightcove_setting) %>
              <%= link_to_edit @brightcove_setting, :no_text => true, url: edit_admin_brightcove_settings_path() %>
            <% end %>

            <% if can?(:destroy, @brightcove_setting) %>
              <%= link_to_delete @brightcove_setting, :no_text => true, url: admin_brightcove_settings_path() %>
            <% end %>
          </td>
        </tr>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
                 resource: Spree::BrightcoveSetting,
                 new_resource_url: new_admin_brightcove_settings_path %>
  </div>
<% end %>

app/views/spree/shared/_player.html.erb
<%brightcove_account_id = get_brightcove_player().try(:brightcove_account_id)
brightcove_player_id = get_brightcove_player().try(:brightcove_player_id)
%>

<video id="myPlayerID"
  data-video-id="<%= reference_id%>"
  data-account="<%= brightcove_account_id%>"
  data-player="<%= brightcove_player_id%>"
  data-embed="default"
  data-application-id
  class="video-js"
  controls></video>

  <script src="//players.brightcove.net/<%= brightcove_account_id%>/<%= brightcove_player_id%>_default/index.min.js"></script>
  <script src="//players.brightcove.net/videojs-overlay/lib/videojs-overlay.js"></script>